### ISSUE TITLE
Here's the info about creating presets and L-systems.

### ISSUE THREAD

**Issue by stillpointx** [WannesMalfait/Blender-Add-ons#16]
**From ChatGPT**
create presets for blender using python

You can create Blender presets using Python by utilizing the Blender Python API. The Blender Python API provides a way to interact with Blender, allowing you to automate tasks, create custom tools, and create new functionality.

Here's an example of how you could create a preset for a simple material in Blender:

```
import bpy

def create_material_preset():
    # Create a new material
    material = bpy.data.materials.new(name="My Material")
    material.diffuse_color = (0.8, 0.3, 0.3)
    material.specular_intensity = 0.5

    # Save the material as a preset
    bpy.data.materials.write_preset(filepath="My Material.py", preset_name="My Material")

# Call the function to create the preset
create_material_preset()
```

Once you run this script, it will create a material with the specified properties and save it as a preset with the file name "My Material.py". You can then load this preset into Blender by going to the "Presets" tab in the Properties window and clicking on the "Import Preset" button.

Also

create presets for blender addon using python

You can create presets for Blender addons using Python by utilizing the Blender Python API. The Blender Python API provides a way to interact with Blender, allowing you to automate tasks, create custom tools, and create new functionality.

Here's an example of how you could create a preset for a simple Blender addon:

```

import bpy

def create_addon_preset():
    # Define the preset data
    preset_data = {
        "name": "My Addon",
        "category": "My Category",
        "bl_idname": "my_addon.my_operator",
        "description": "My Addon Description",
        "default_closed": False,
        "preferences": [
            {
                "type": "int",
                "name": "My Int Property",
                "description": "My Int Property Description",
                "default": 42
            },
            {
                "type": "float",
                "name": "My Float Property",
                "description": "My Float Property Description",
                "default": 3.14
            },
        ],
    }

    # Save the preset data
    bpy.ops.script.python_file_preset(filepath="My Addon.py", preset_data=preset_data)

# Call the function to create the preset
create_addon_preset()
```

Once you run this script, it will save the preset data in a file with the name "My Addon.py". You can then load this preset into Blender by going to the User Preferences, then the Add-ons tab, and clicking on the "Install Add-on from File" button. The addon will appear in the specified category and can be enabled or disabled like any other addon in Blender.

**Comment by WannesMalfait** [comment]
Sadly chatGPT is not really giving a correct solution here (even though it sounds very confident). I looked into this a bit more, and operator presets just have to be added manually by the user, or bundled with blender itself.

**Comment by stillpointx** [comment]
Thanks for the update.  I guess ChatGPT has a ways to go yet.
