### ISSUE TITLE
Pasting text into formula window adds random spaces

### ISSUE THREAD

**Issue by stillpointx** [WannesMalfait/Blender-Add-ons#27]
I'm using version 2.0 with Blender 4.0.2.  When I copy and paste text from the Blender script editor to the formula window it adds spaces randomly.  Do you have a workaround for this? I'm testing different algebras (Quaternions / Octonions) using Blender and geometry nodes to visualize the effect it has on different shapes.

![image](https://github.com/WannesMalfait/Blender-Add-ons/assets/28985314/ee64d3c8-0612-4193-88d3-aec54eb8c913)

![screenshot-December-08-2023-02-05-15](https://github.com/WannesMalfait/Blender-Add-ons/assets/28985314/cabb72c7-1e22-46db-94f8-d9e502de8659)

Example: 
```
qnew_w=(q1_w​*q2_w​)-(q1_i​*q2_i)​-(q1_j​*q2_j​)-(q1_k​*q2_k​)
qnew_i=(q1_w​*q2_i)​+(q1_i​*q2_w​)+(q1_j​*q2_k)​-(q1_k​*q2_j​)
qnew_j=(q1_w​*q2_j​)-(q1_i​*q2_k​)+(q1_j​*q2_w​)+(q1_k​*q2_i​)
qnew_k=(q1_w​*q2_k​)+(q1_i​*q2_j​)-(q1_j​*q2_i​)+(q1_k​*q2_w​)
```

![screenshot-December-08-2023-02-04-34](https://github.com/WannesMalfait/Blender-Add-ons/assets/28985314/5e4dfbc0-a524-48f4-a030-07aa5a2a8b3a)

![image](https://github.com/WannesMalfait/Blender-Add-ons/assets/28985314/72b132a3-4995-4599-9f1b-856cf918679d)

This is my new favorite add-on since this simplifies me creating and connecting large math node groups.

**Comment by WannesMalfait** [comment]
Looks like the code you copy-pasted contains a bunch of zero-width spaces (all the `\\u200b`:
```
b'qnew_w=(q1_w\\u200b*q2_w\\u200b)-(q1_i\\u200b*q2_i)\\u200b-(q1_j\\u200b*q2_j\\u200b)-(q1_k\\u200b*q2_k\\u200b)
qnew_i=(q1_w\\u200b*q2_i)\\u200b+(q1_i\\u200b*q2_w\\u200b)+(q1_j\\u200b*q2_k)\\u200b-(q1_k\\u200b*q2_j\\u200b)
qnew_j=(q1_w\\u200b*q2_j\\u200b)-(q1_i\\u200b*q2_k\\u200b)+(q1_j\\u200b*q2_w\\u200b)+(q1_k\\u200b*q2_i\\u200b)
qnew_k=(q1_w\\u200b*q2_k\\u200b)+(q1_i\\u200b*q2_j\\u200b)-(q1_j\\u200b*q2_i\\u200b)+(q1_k\\u200b*q2_w\\u200b)
```
https://unicode-explorer.com/c/200B

I will add a filter to clipboard pasting that gets rid of unwanted characters like this. When that is done I will close the issue, and make a patch release.
