### ISSUE TITLE
Add support for infix notation in math_formula.py

### ISSUE THREAD

**Issue by WannesMalfait** [WannesMalfait/Blender-Add-ons#3]
# The problem
Currently the formula that the user types has to be in postfix notation, i.e. the operator comes after the operands. Although this makes it efficient to parse and evaluate into nodes, from a users point of view this is an inconvenience. For people who have never worked with postfix notation it can be very easy to make mistakes without understanding where it comes from.

## Solution
Preferably the formula can be typed in infix notation, which can then be converted to postfix by the add-on itself. This will require changing of the syntax (i.e. using parentheses for vectors will probably need to be changed)

## Syntax
The current syntax is a bit messy. It is therefore important to design a good and consistent syntax for normal and attribute math nodes.

### General syntax
This is the proposed syntax for infix notation:
- `(` and `)` can be used to give precedence in the order of operations, e.g `(1 + 2) * 4` evaluates to `12` and not `9`.
- Common operators which have a special symbol can be placed in between their operands. These operators are: `> < + - * / % ^ **`, These also have a priority level.  The priorities are as follows: `function call` > `( )` > `** ^` > `* / %` > `+ -` > `< >`
- The same operators can also be used as vector math operations by prefixing it with a `v`. So `*` becomes `v*`.
- All other functions have to be called in the normal way present in most programming languages: `function_name(arg1, arg2, arg3)`, with the arguments separated by comma's. It is possible that the same function has multiple aliases, e.g. `sine` and `sin` are the same function. The arguments can be expressions themselves., e.g. `sin(4 * 5)` is valid syntax.
- Creating a vector is done with `{ }`, with the components separated by comma's. So the vector with components `4` `5` and `7` would be written as `{4, 5, 7}`. If a vector contains inputs that aren't floats, a `Combine XYZ` node is added instead. This means that `{4, 5, 7*8}` will be a `Combine XYZ` node, because the final component is an expression.
- In blender, it is possible to type in mathematical equations in the float fields. To also provide this support for the user typing in the formula (If they need an input which is `pi/4` for example), we add the special function `!()`, which will evaluate the expression inside the parentheses with python. The expression must be a python expression that evaluates to a number. For convenience, the python `math` library will be imported so common constants and mathematical functions are available.
- The semicolon, `;`, marks the end of every statement. 
- If a function takes in a vector as an argument, but a float is given, then it is automatically converted to a vector. So `vsin(10)` is treated as `vsin({10,10,10})`.
- `=` can be used to assign/declare variables. See below for specific rules.

### Syntax specific to normal math nodes:
- The `let` keyword can be used to declare variables without specifying a value. For example `let x;`. Declaring a variable is the same as adding an input node, with the label set to the variable name. Later uses of that variable name will connect the output of that input node to the appropriate input socket. 
- To create a `Separate XYZ` node with specific variable names you can use the syntax `let {name_1,name_2,name_3} = some_name;`. The right hand side can be an expression. Otherwise `.` followed by any of `x`, `y` or `z`, will create a `Separate XYZ` node from the result of the left hand side. Example: `fract(scale(coords, 10)).xy`.
- All other kinds of variables can be assigned a value without needing to use `let`.  Example: `z = sin(x);`, will store the output socket of the right hand side in the variable `z`, which can then be used later.
- Anything that is not part of the general syntax will be seen as a placeholder and automatically turned into the number `0`. For example, the input `let {a,b,c}= undeclared;` would be treated as `let {a,b,c} = 0`.

### Syntax specific to attribute math nodes:
- Unlike with normal math nodes, in this case the leftover words will be treated as input attributes.
- The operator `=` can be used to set the name of the next attribute math operation. For example: `z = sin(x);` would create an attribute math node with the operation set to `SINE`, the input set to the attribute `x`, and the result set to the attribute `z`. This does not return a value, the result name has to be retyped to be used by another function. So, continuing on the previous example, if we now wanted to multiply `z` with `x` we'd have to do this: `z = sin(x); z*x;`.
- Appending `.` followed by any of `x`, `y` or `z` to an attribute, will create a `Separate XYZ` node with the input set to the attribute and the resulting components set if they appeared after the `.`. For example `position.yz` creates a `Separate XYZ` node with the input attribute set to `position`, and the outputs: `Result Y` and `Result Z` set to `y` and `z` respectively. The attribute output, `Result X`, is left empty.  Like with the `Combine XYZ` node, this will not return a value that can be used in the formula indirectly, instead, the attributes have to be retyped. 
- Like with normal math nodes, `let {x_name, y_name, z_name}` followed by a vector of three names  can be used to create a `Separate XYZ` node. The three components of the vector are treated as attribute names, and not as expressions to be evaluated. Example: `{ ,pos_y, pos_z} = position;`, creates attributes `pos_y` and `pos_z`, set to the `y` and `z` components of the attribute `position`.

### Examples:
- `position.xy; z = x^2 + y^2; position = {x, y, z};`
- `vfract(scale(coords, 10)) v- 0.5;`

### Possible additions for the future
- Parallel operations with `||`, i.e. use the output of a node for multiple nodes.
- Alternative syntax for clamp: `4<x<5` instead of `clamp(x,4,5)`
- Support for `Mix RGB` by calling the specific blending modes.
- Support for other common functions in formulas like `clamp`, `lerp`, `smoothstep`,...
- Adding a driver expression with `#( )` (similar to python expression syntax)
- Expressions which expand to more complicated expressions. Think of things like `add(x, y,z)` which expands to `x+y+z`  for example. Maybe even allow user defined macros. Like `rect_tiling(10)` expands to `vfract(scale(coords, 10)) v- 0.5`. Or things like capitalizing an attribute means that the operations on it have to be treated like vector math operations (`pos * 5` is normal multiply, but `POS * 5` is vector math scale).

## Things to do
The parsing code will be based on [this](https://faculty.washington.edu/jstraub/dsa/aexp/) and [this](https://github.com/munificent/craftinginterpreters/tree/master/c).
- [x] Create python abstractions for the different kinds of tokens
- [x] Create a scanner class that turns a string into an array of tokens.
- [x] Convert the array of tokens into a postfix expression.
- [x] Adapt the syntax highlighting code to be more dynamic.
- [x] Adapt the operators to work with the new kinds of tokens.
- [x] Figure out a way to deal with invalid syntax. (Where, when and how to display warnings and errors)
- [x] Testing

## Where to find the new updates
The code to add this will be added in a separate branch named `infix`. Once everything is working it will be merged with the main branch.

**Comment by Zawarud** [comment]
from youtube:
better use the tipical convention: 
1) if we separate axis we need to write  kuje this :  z= x^2+y^2 ;  1<x<2 ; 3<y<4
and  the  **;**  as a system of equations
2) if we use vector we use UPPERCASE like POS : POS = POS*0.20  (scaling)

**Comment by WannesMalfait** [comment]
>     1. if we separate axis we need to write  kuje this :  z= x^2+y^2 ;  1<x<2 ; 3<y<4
>        and  the  ;  as a system of equations

With a system of equations, do you just mean multiple equations after each other, or something like a [linear system of equations](https://en.wikipedia.org/wiki/System_of_linear_equations)? The goal of the add-on is not to be able to solve any kind of equations. 

If you meant multiple equations after each other, than it does make sense to have a symbol like `;` to be able to suppress the result of the previous node. This would mean that the result is not used as an argument for the next function. So `x+y; * 7` would be the same as doing `x + y 0 * 7`. 

Hopefully I understood that correctly. 

>     2. if we use vector we use UPPERCASE like POS : POS = POS*0.20  (scaling)

I don't think that this is a good idea. In my opinion it's better if the type of operation has to be specified. Otherwise we'd have to basically do operator overloading, which could create all sorts of unforeseeable problems. This also requires the user to use upper case for vector attributes and lower case for float attributes, while I think that the convention is to use `snake_case` for everything.

**Comment by WannesMalfait** [comment]
I do think that it might be a good idea to use `=` as assignment instead of `->`.  So that would mean that `sin(x) -> z`, becomes this: `z = sin(x)` instead, which is a much more conventional way of doing assignment.

Thanks for the suggestions

**Comment by Zawarud** [comment]
1. I mean that with 2° and 3°  equations we set the size of the plane(proportion scaling), with the 1° we set z axis points. we dont solve nothing, we dont have unknown variables. the exactly nodes order is : 2,3° ; 1° 
2.  for example(in this case we cant write bold):  https://people.eecs.ku.edu/~jrmiller/Courses/VectorGeometry/VGNotation/index.html 
3.  for set  a step by step operations  you can ues || . But with  ;  you set a parallel operation. 
4. Using this image: I) D || A      II) B ; C   III) the equation represent a math node.
![image](https://user-images.githubusercontent.com/53933533/109144022-f7a0ac00-7760-11eb-8861-8a9d013b7fdd.png)

**Comment by WannesMalfait** [comment]
@Zawarud  These are some really cool ideas, but I think that they are not essential for the basic syntax, and are instead part of the possible extensions in the future. I'll add them to that list. Since `||` denotes parallel lines in geometry, it would make more sense for me if that is used to indicate parallel operations, while keeping `;` as an end of statement indicator. I think that it's also important to keep in mind that the add-on is meant for writing simple formulas and not an entire node tree.
