### ISSUE TITLE
function editor on node screen too small to see

### ISSUE THREAD

**Issue by wizbrewery** [WannesMalfait/Blender-Add-ons#5]
Hi been enjoying playing with your addon in conjuction with geometric nodes. I have a high resolution laptop with a small screen,  when I hit shift f your function editor comes up tiny and unreadable,  irrespective of the zooming level of the nodes. Not a biggy as your add math formula window does the job,  cheers

**Comment by WannesMalfait** [comment]
You can change the font size in the add-on preferences. Try setting it to something like 30. Thanks for the feedback.
![addon preferences font size](https://user-images.githubusercontent.com/46323945/110803158-306f7380-827f-11eb-8641-7152f4c71bf0.png)

**Comment by wizbrewery** [comment]
Perfect,  missed that one,  thank you. :)
