### ISSUE TITLE
3D parametric equations with (u,v) multi-variables. with Math Formula add-on

### ISSUE THREAD

**Issue by stillpointx** [WannesMalfait/Blender-Add-ons#6]
Wow, this is great!!  Will you be adding an option to do 3D parametric equations with (u,v) multi-variables.  Being able to do this will open up mathematical animation in a big way.

One example:
```
for i in range (0, num_x):
        for j in range(0,num_y):
            # nomalize range
            
            # u = 8*(i/num_x-1/2)
            u = 2*math.pi*(i/(num_y-1)-1/2)
            v = 2*math.pi*(j/(num_y-1)-1/2)
            
            x = math.sqrt(1+u**2)*math.cos(v)*uval_a/2
            y = math.sqrt(1+u**2)*math.sin(v)*uval_a/2
            z = uval_b*(u)/(2*math.pi/1)
            # uval_a gives the diameter of center hole
            # uval_b gives the height
```
            

[https://i.imgur.com/aHCi2U7.png](url)
![aHCi2U7](https://user-images.githubusercontent.com/28985314/112748265-add9fa00-8f88-11eb-828b-9eaeac96f61b.png)

**Comment by WannesMalfait** [comment]
### Solution
You can use the following formula to get the same result as the code.
![one leaf hyperboloid](https://user-images.githubusercontent.com/46323945/112755023-35eaee80-8fdf-11eb-8cf5-5c927c624a3a.png)
These are the final nodes (grid node added manually):
![nodes](https://user-images.githubusercontent.com/46323945/112755086-777b9980-8fdf-11eb-85d8-8253fb8f6d44.png)
![resulting geometry](https://user-images.githubusercontent.com/46323945/112755450-076e1300-8fe1-11eb-9824-5abcabe715c7.png)

### Note
I noticed a bug while using this formula (separate XYZ wasn't working properly), so you'll need to wait for the newer version for it to work. You can work around it with this formula, which gives the same result, but works:
![hack formula](https://user-images.githubusercontent.com/46323945/112755293-4c457a00-8fe0-11eb-9ddd-67313f10a957.png)

## Future
In the future I will make it possible to place the nodes in a group, where the formula can be edited on demand, without having to manually delete and reconnect nodes. For now I'll leave the issue open.
